### ISSUE TITLE
DoT Related Designer Effects

### ISSUE THREAD

**Issue by Xendran** [ScoreWin/letsgoraiding#54]
There are some effects I'd like to see in the designer that will open up more design space for current and future cards, as well as bosses. These are:

REDUCE_BLEED
REDUCE_POISON
REDUCE_IGNITE

These will reduce the DoT stack by X.

PROGRESS_BLEED
PROGRESS_POISON
PROGRESS_IGNITE

These will trigger the DoT stack X amount of times, in the same way that would happen if it triggered naturally.

==EXAMPLES==

--POISON / BLEED--

Example 1.
A hero has Poison 8. They are hit with PROGRESS_POISON with a payload of value 1.
They lose 8 life from Poison and are now at Poison 7.

Example 2.

A hero has Poison 10. A raid boss hits them with PROGRESS_POISON with a payload value of 10.
They lose a total of 55 life from all 10 poisons triggering. They now have no Poison stacks.

--IGNITE--
A hero has two stacks of Ignite 5. They are hit with PROGRESS_IGNITE with a payload value of 2.
Both stacks of Ignite 5 will trigger, and the hero will lose 5 life twice for a total of 10. They now have no Ignite stacks.

**Comment by stephencorwin** [comment]
Reducing a specific amount of a dot rather than all of it, might feel weird to print on a card. I will go ahead and implement both of these because it cleans up the built-in engine mechanics a bit. However, I would caution having any player ability that specific removes some, but not all of a specific dot.
